### ISSUE TITLE
Missing declaration for base class' `$icon`

### ISSUE THREAD

**Issue by lat9** [lat9/favorites_wishlist_support#5]
Seeing logs like the following under PHP 8.2.
```
[04-May-2023 00:49:28 UTC] Request URI: /zc158/index.php?main_page=index&cPath=23&sort=20a, IP address: 127.0.0.1, Language id 1
#0 C:\xampp\htdocs\zc158\includes\classes\class.favorites.php(996): zen_debug_error_handler()
#1 C:\xampp\htdocs\zc158\includes\classes\observers\FavoritesWishlistObserver.php(166): favorites->getFavoritesIcon()
#2 C:\xampp\htdocs\zc158\includes\classes\traits\NotifierManager.php(87): FavoritesWishlistObserver->update()
#3 C:\xampp\htdocs\zc158\includes\templates\bootstrap\common\tpl_main_page.php(301): base->notify()
#4 C:\xampp\htdocs\zc158\index.php(94): require('C:\\xampp\\htdocs...')
--> PHP Deprecated: Creation of dynamic property favorites::$icon is deprecated in C:\xampp\htdocs\zc158\includes\classes\class.favorites.php on line 996.
```

**Comment by lat9** [comment]
v6.0.1 now released; closing.
